openapi: "3.0.2"

info:
  title: "ohapo API"
  version: "0.0.1"

servers:
  - url: "http://localhost:3031/"
    description: "ローカル環境 API"

# API仕様一覧
paths:
  "/categories":
    get:
      tags:
        - categories
      summary: "ユーザが選択できるカテゴリの一覧を返す"
      parameters: []
      responses:
        "200":
          description: "Categoryモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
                example:
                  - id: 1
                    category_name: カテゴリ1
                  - id: 2
                    category_name: カテゴリ2
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/whatdays":
    get:
      tags:
        - whatdays
      summary: "昨日、今日、明日の記念日を返す"
      parameters: []
      responses:
        "200":
          description: "Whatdayモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Whatday"
                example:
                  - date: "2019-09-20"
                    description: "バスの日"
                  - date: "2019-09-21"
                    description: "ファッションショーの日"
                  - date: "2019-09-22"
                    description: "ワンウェブデー"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/user":
    get:
      tags:
        - user
      summary: "全ユーザ情報を返す"
      parameters: []
      responses:
        "200":
          description: "ユーザモデルのリスト"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/responses/ExampleUser"
        "400":
          $ref: "#/components/responses/UnexpectedError"

    post:
      tags:
        - user
      summary: "ユーザ情報を作成する"
      parameters: []
      requestBody: # リクエストボディ
        description: "作成するユーザモデル"
        content:
          application/json:
            schema:
              $ref: "#/components/responses/ExampleUserWithoutId"
      responses:
        '201':
          description: "ユーザ情報作成成功"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/user/{userId}":
    get:
      tags:
        - user
      summary: "ユーザ情報を返す"
      parameters:
        - name: userId
          in: path
          description: "ユーザID"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "ユーザモデル"
          content:
            "application/json":
              schema:
                $ref: "#/components/responses/ExampleUser"
        "400":
          $ref: "#/components/responses/UnexpectedError"

    put:
      tags:
        - user
      summary: "ユーザ情報を更新する"
      parameters: 
        - name: userId
          in: path
          description: "ユーザID"
          required: true
          schema:
            type: integer
      requestBody: # リクエストボディ
        description: "作成するユーザモデル"
        content:
          application/json:
            schema:
              $ref: "#/components/responses/ExampleUserWithoutId"
      responses:
        "200":
          description: "ユーザ情報更新成功"
        "400":
          $ref: "#/components/responses/UnexpectedError"

    delete:
      tags:
        - user
      summary: "ユーザ情報を消す"
      parameters:
        - name: userId
          in: path
          description: "ユーザID"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "ユーザ情報削除成功"
        "400":
          $ref: "#/components/responses/UnexpectedError"

  "/healthcheck":
    get:
      tags:
        - healthcheck
      summary: "正常ならOKを返す"
      responses:
        "200":
          description: "正常"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/HealthCheck"
        "400":
          $ref: "#/components/responses/UnexpectedError"

# 扱うコンポーネント一覧
components:
  schemas:
    Category:
      description: "カテゴリ"
      type: object
      required: #必須フィールド
        - id
        - category_name
      properties:
        id:
          type: integer
        category_name:
          type: string
    
    Whatday:
      description: "記念日"
      type: object
      required:
        - date
        - description
      properties:
        date:
          type: string
          format: date
        description:
          type: string

    User:
      description: "ユーザ"
      type: object
      required:
      properties:
        id:
          title: "User Id"
          type: integer
        user_name:
          title: "User Name"
          type: string
        age:
          title: "User age"
          type: integer
        gender:
          title: "User Gender"
          type: string
        location:
          title: "User Location"
          type: string
        zip_code:
          title: "User ZipCode"
          type: string
          pattern: "¥d{3}-¥d{4}"

    Error:
      description: "エラー"
      type: object
      required:
        - message
        - code
      properties:
        message:
          title: "Err Msg"
          type: string
        code:
          title: "Status Code"
          type: integer
          minimum: 100
          maximum: 600

    HealthCheck:
      description: "HealthCheck"
      type: object
      required:
        - result
      properties:
        result:
          title: "result"
          type: string
          example: "ok"


  # 汎用的に使うものはまとめておく
  responses:
    UnexpectedError:
      description: "予期しないエラー"
      content:
        "application/json":
          schema:
            tyope: object
            items:
              $ref: "#/components/schemas/Error"
            example:
              message: "データが見つからないとか"
              code: 400

    ExampleUser:
      items:
        $ref: '#/components/schemas/User'
      example:
        id: 101
        user_name: John Do
        age: 30
        gender: "man"
        location: "Shinagawa, Tokyo"
        zip_code: "123-4567"

    ExampleUserWithoutId:
      items:
        $ref: '#/components/schemas/User'
      example:
        user_name: John Do
        age: 30
        gender: "man"
        location: "Shinagawa, Tokyo"
        zip_code: "123-4567"

tags:
  - name: categories
    description: "カテゴリ一覧機能"
  - name: whatdays
    description: "記念日機能"
  - name: user
    description: "ユーザ操作機能"
  - name: healthcheck
    description: "HealthCheck機能"
